export const UPDATE_LOCATION_NAME = 'UPDATE_LOCATION_NAME';
export const UPDATE_WEATHER_INFO = 'UPDATE_WEATHER_INFO';
export const UPDATE_FORECAST_INFO = 'UPDATE_FORECAST_INFO';
export const ADD_FAVORITE_LOCATION = 'ADD_FAVORITE_LOCATION';
export const REMOVE_FAVORITE_LOCATION = 'REMOVE_FAVORITE_LOCATION';
